---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang, tag: 1.13.4}

inputs:
  - name: terraform-provider-alicloud
  - name: goreleaser
  - name: aliyun-cli
outputs:
  - name: terraform-provider-alicloud
run:
  path: terraform-provider-alicloud/ci/tasks/publish.sh
params:
  GITHUB_TOKEN: ""
  GPG_FINGERPRINT: ""
  DING_TALK_TOKEN: ""
  ALICLOUD_ACCESS_KEY: ""
  ALICLOUD_SECRET_KEY: ""
  BUCKET_NAME: "terraform-pipeline"
  BUCKET_REGION: "eu-central-1"

